from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

dados_rotulados = [
    {"texto": "Global climate change has rippling effects on our environment, impacting where plants, animals, and humans can live. The USGS studies how climate change affects natural places and provides solutions to help protect fish, wildlife, and habitats.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Everything in the natural world is connected. Animals eat plants, insects pollinate flowers, microbes break down dead things. Living things are also connected to the “non-living” parts of their environments they use rocks for shelter, they depend on rain to bloom, they hibernate when it gets cold. Together, these living and non-living components make up an ecosystem.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Climate helps shape ecosystems. Things like average temperatures, humidity, and rainfall determine where plants and animals live. If a regions climate changes, the ecosystems change as well.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Scientists at the USGS study how climate change affects the Nations wildlife, fish, plants, and ecosystems. We also help resource managers develop and implement strategies to allow plants and animals to survive and thrive in new conditions. We generate our science side-by-side with partners to ensure results and tools are directly applicable to on-the-ground conservation, restoration, and management decisions. USGS climate science is used to protect natural areas across the country, from local-scale conservation decisions to national park climate scenario planning.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "USGS science particularly focuses on helping resource managers, conservation agencies, and Indigenous peoples implement climate adaptation practices that intentionally help preserve species and landscapes under new climate conditions. For example, this could involve building sea walls to keep out rising sea levels, or planting drought-tolerant grasses in dry areas. Adapted landscapes may not look exactly the way they used to, but ideally the modifications allow them to continue to support the natural and human communities that rely on them. USGS scientists also use monitoring, field work, and modeling to understand how species naturally adapt to climate change, called adaptive capacity.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Model species range shifts under potential future conditions", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Identify species particularly vulnerable to climate change", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Identify areas relatively buffered from climate change (“climate refugia”) that may help vulnerable species survive", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Develop climate adaptation strategies and inform implementation for species and ecosystems""Support DOI partners in incorporating climate information into conservation and management decisions, such as Species Status Assessments (SSAs) or State Wildlife Action Plans (SWAPs)", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Understand climate-induced shifts in phenology and identify potential management solutions""Protect ecosystem services important to communities""Measure species natural abilities to adapt to climate change (adaptive capacity)""Support climate adaptation efforts of Tribal Nations and other Indigenous peoples", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "The USGS has hundreds of publications on climate change effects on plants, animals, and ecosystems. Explore some of our favorites below!""Explore some of the many USGS science projects on climate change effects on plants, animals, and ecosystems.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "An interactive geonarrative exploring the Fish and Climate Change (FiCli) Database.""Check out some of the amazing USGS photos, videos, podcasts, and webinars on plants, animals, ecosystems, and climate change.""One Health is a collaborative approach working at the local, regional, national, and global levels with the goal of achieving optimal health...""Northeast CASC supported researchers and partners propose a framework designed to increase collaboration among scientists, practitioners, and policy...""A new publication co-authored by National and Northwest CASC scientists provides evolutionary biologists with options for how to make their research...""Marine heatwaves are global phenomena that can have major impacts on the structure and function of coastal ecosystems. The 2014-2016 northeast Pacific...", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Everything in the natural world is connected. Animals eat plants, insects pollinate flowers, microbes break down dead things. Living things are also connected to the “non-living” parts of their environments they use rocks for shelter, they depend on rain to bloom, they hibernate when it gets cold. Together, these living and non-living components make up an ecosystem.", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "The USGS One Health Approach to WildLife Disease and Environmental Change, is a collaborative approach working at the local, regional, national, and global levels with the goal of achieving optimal health...", "categoria": "Notícias", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Sensitivity of headwater streamflow to thawing permafrost and vegetation change in a warming Arctic Climate change has the potential to impact headwater streams in the Arctic by thawing permafrost and subsequently altering hydrologic regimes and vegetation distribution, physiognomy and productivity. Permafrost thaw and increased subsurface flow have been inferred from the chemistry of large rivers, but there is limited empirical evidence of the impacts to headwater streams. Here we demonstrate hAuthorsJoshua C. Koch, Ylva Sjöberg, Jonathan A. O'Donnell, Michael P. Carey, Pamela Sullivan, A. TerskaiaByAlaska Science Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Evaluation of MPA designs that protect highly mobile megafauna now and under climate change scenarios Marine protected area(MPA) designs, including large-scale MPAs (LSMPAs; >150,000km2), mobile MPAs (fluid spatiotemporal boundaries), and MPA networks, may offer different benefits to species and could enhance protection by encompassing spatiotemporal scalesof animal movement. We sought to understand how well LSMPAs could benefit nine highly-mobile marine species in the tropics now and into theAuthorsMorgan Elizabeth Gilmour, Josh Adams, Barbara A. Block, Jennifer E. Caselle, A. M. Friedlander, Edward T. Game, E. L. Hazen, Nick D. Holmes, Kevin D. Lafferty, S. M. Maxwell, Douglas J. McCauley, E. M. Oleson, Kenneth H. Pollock, S. A. Shaffer, N. H. Wolff, Alex WegmannByEcosystems Mission Area, Western Ecological Research Center (WERC)", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "A climate-mediated shift in the estuarine habitat mosaic limits prey availability and reduces nursery quality for juvenile salmon The estuarine habitat mosaic supports the reproduction, growth, and survival of resident and migratory fish species by providing a diverse portfolio of unique habitats with varying physical and biological features. Global climate change is expected to result in increasing temperatures, rising sea levels, and changes in riverine hydrology, which will have profound effects on the extent and compositAuthorsMelanie J. Davis, Isa Woo, Christopher S. Ellings, Sayre Hodgson, David Beauchamp, Glynnis Nakai, Susan E. W. De La CruzByEcosystems Mission Area, Cooperative Research Units, Species Management Research Program, Western Ecological Research Center (WERC), Western Fisheries Research Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Potential effects of climate change on snail kites (Rostrhamus sociabilis plumbeus) in Florida The snail kite (Rostrhamus sociabilis plumbeus), an endangered, wetland-dependent raptor, is highly sensitive to changes in hydrology. Climate-driven changes in water level will likely affect snail kite populations—altering reproductive success and survival rates. Identifying the mechanisms mediating the direct and indirect effects of climate on snail kite populations and the range of future climaAuthorsMarta P. Lyons, Olivia E. LeDee, Ryan Boyles", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Conservation under uncertainty: Innovations in participatory climate change scenario planning from U.S. national parks The impacts of climate change (CC) on natural and cultural resources are far-reaching and complex. A major challenge facing resource managers is not knowing the exact timing and nature of those impacts. To confront this problem, scientists, adaptation specialists, and resource managers have begun to use scenario planning (SP). This structured process identifies a small set of scenarios—descriptionAuthorsBrian W. Miller, Gregor W. Schuurman, Amy Symstad, Amber C Runyon, Brecken C. RobbByEcosystems Mission Area, Climate Adaptation Science Centers, Northern Prairie Wildlife Research Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Climate change adaptation thinking for managed wetlands Climate change presents new and ongoing challenges to natural resource management. To confront these challenges effectively, managers need to develop proactive adaptation strategies to prepare for and deal with the effects of climate change. We engaged managers and biologists from several midwestern U.S. Fish and Wildlife Service field stations to understand recent and future climate change effectAuthorsJohn T. Delaney, Kristen L. Bouska, Josh D. EashByEcosystems Mission Area, Upper Midwest Environmental Sciences Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Perils of life on the edge: Climatic threats to global diversity patterns of wetland macroinvertebrates Climate change is rapidly driving global biodiversity declines. How wetland macroinvertebrate assemblages are responding is unclear, a concern given their vital function in these ecosystems. Using a data set from 769 minimally impacted depressional wetlands across the globe (467 temporary and 302 permanent), we evaluated how temperature and precipitation (average, range, variability) affects the rAuthorsLuis B. Epele, Marta G. Grech, Emilio A. Williams-Subiza, Cristina Stenert, Kyle I. McLean, Hamish S. Greig, Leonardo Maltchik, Mateus M. Pires, Matthew S. Bird, Aurelie Boissezon, Dani Boix, Eliane Demierre, Patricia E. García, Stephanie Gascón, Michael Jeffries, Jamie M. Kneitel, Olga Loskutov, Luz M. Manzo, Gabriela Mataloni, Musa C. Mlambo, Beat Oertli, Jordi Sala, Erica E. Scheibler, Haitao Wu, Scott A Wissinger, Darold P. BatzerByEcosystems Mission Area, Climate Research and Development Program, Northern Prairie Wildlife Research Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "The impact of future climate on wetland habitat in a critical migratory waterfowl corridor of the Prairie Pothole Region Depressional wetlands are extremely sensitive to changes in temperature and precipitation, so understanding how wetland inundation dynamics respond to changes in climate is essential for describing potential effects on wildlife breeding habitat. Millions of depressional basins make up the largest wetland complex in North America known as the Prairie Pothole Region (PPR). The wetland ecosystems thaAuthorsOwen P. McKennaByEcosystems Mission Area, Climate Research and Development Program, Northern Prairie Wildlife Research Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Stoneflies in the genus Lednia (Plecoptera: Nemouridae): Sentinels of climate change impacts on mountain stream biodiversity Rapid recession of glaciers and snowfields is threatening the habitats of cold-water biodiversity worldwide. In many ice-sourced headwaters of western North America, stoneflies in the genusLednia(Plecoptera: Nemouridae) are a prominent member of the invertebrate community. With a broad distribution in mountain streams and close ties to declining glacier cover,Lednia has emerged as a sentinel ofAuthorsMatthew D. Green, Lusha M. Tronstad, J. Joseph Giersch, Alisha A. Shah, Candace E. Fallon, Emilie Blevins, Taylor Kai, Clint C. Muhlfeld, Debra S. Finn, Scott HotalingByEcosystems Mission Area, Cooperative Research Units, Northern Rocky Mountain Science Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Long-term variation in polar bear body condition and maternal investment relative to a changing environment In the Arctic, warming air and ocean temperatures have resulted in substantial changes to sea ice, which is primary habitat for polar bears (Ursus maritimus). Reductions in extent, duration, and thickness have altered sea ice dynamics, which influences the ability of polar bears to reliably access marine mammal prey. Because nutritional condition is closely linked to population vital rates, a progAuthorsTodd C. Atwood, Karyn D. Rode, David C. Douglas, Kristin S. Simac, Anthony Pagano, Jeffrey F. BromaghinByEcosystems Mission Area, Alaska Science Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Response of forage plants to alteration of temperature and spring thaw date: Implications for geese in a warming Arctic Changes in summer temperatures in Arctic Alaska have led to longer and warmer growing seasons over the last three decades. Corresponding with these changes in climate, the abundance and distributions of geese have increased and expanded over the same period. We used an experimental approach to assess the response of goose forage plants to simulated environmental change. We subjected Carex subspathAuthorsPaul L. Flint, Brandt W. MeixellByEcosystems Mission Area, Land Management Research Program, Alaska Science Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Reduced quality and synchronous collapse of forage species disrupts trophic transfer during a prolonged marine heatwave The Gulf of Alaska forage fish community includes a few key species that differ markedly in their timing of spawning, somatic growth and lipid storage, and in their migration behavior. This diversity in life history strategies facilitates resilience in marine food webs because it buffers predators against the naturally high variance in abundance of pelagic forage fish populations by decreasing theAuthorsMayumi L. Arimitsu, John F. Piatt, Scott Hatch, Rob Suryan, Sonia Batten, Mary Anne Bishop, Rob Campbell, Heather Coletti, Dan Cushing, Kristen Gorman, Stormy Haught, Russell Hopcroft, Kathy Kuletz, Caitlin Elizabeth Marsteller, Caitlin McKinstry, David McGowan, John Moran, R. Scott Pegau, Anne Schaefer, Sarah K. Schoen, Jan Straley, Vanessa R. von BielaByEcosystems Mission Area, Land Management Research Program, Alaska Science Center", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "Resist-Accept-Direct (RAD) Framework The Resist-Accept-Direct (RAD) framework is a decision-making tool that helps resource managers make informed strategies for responding to ecological changes resulting from climate change.ByClimate Adaptation Science Centerslink September 26, 2023  Resist-Accept-Direct (RAD) FrameworkThe Resist-Accept-Direct (RAD) framework is a decision-making tool that helps resource managers make informed strategies for responding to ecological changes resulting from climate change", "categoria": "climate", "agencia":"USGS", "topico": "impacts-on-plants-and-animals"},
    {"texto": "“Greenhouse” gases occur naturally in the Earths atmosphere. They help regulate the planets temperature, like how the glass in a greenhouse retains heat or a blanket reflects your body heat to keep you warm. Adding more greenhouse gases into the atmosphere, like we do when burning fossil fuels, acts like putting a thicker blanket on the planet. The thicker the blanket of greenhouse gases, the less heat escapes into space. This causes the planet to get warmer.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "There are also natural sources of greenhouse gases, including volcanic eruptions, geologic seeps from features like hot springs and geothermal vents, thawing permafrost, and forest fires. Climate change and human activities can accelerate natural emissions. Warmer temperatures defrost permafrost and heat up oceans, releasing the carbon long stored in these systems. Wetlands drained for agriculture can rapidly switch from being carbon sinks to being carbon sources. And human ignitions and climate-driven dryness mean long, intense fire seasons, releasing billions of metric tons of carbon dioxide around the world each year.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "The main contributor to climate change is human emissions. Although the greenhouse gases responsible for causing climate change do occur naturally in our atmosphere, the concentrations have been increasing significantly since the 1880s. The increase in the amount of carbon dioxide, in particular, is the biggest culprit that has led to a 1.9-degrees Fahrenheit in the planets average global temperature since the Industrial Revolution.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "One characteristic of climate change that continues to evolve is how we discuss the different factors that contribute to it. Historically, the burning of fossils fuels was the primary focus, as that is the key driver of increased greenhouse gases, particularly carbon. However, as researchers learn more about the ways carbon cycles through the atmosphere, a more nuanced picture is beginning to form. Scientists use color to classify carbon at different points in the carbon cycle based on carbon function, characteristics, and location. This creates a more descriptive framework than traditional organic and inorganic labels - a carbon rainbow, so to speak.""The Colors of Carbon include:", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "Sometimes people may be confused by the difference between weather and climate. A single snowstorm or cold spell does not disprove global warming. Weather refers to short-term atmospheric conditions, while climate is the weather of a specific region averaged over a long period of time. While we expect the weather to change almost daily, a regions climate is normally stable over time. For example, Florida is generally warmer and rainier than Montana, even if on a particular day it is raining in Montana but not in Florida. Climate change refers to long-term changes in a regions climate. In recent years, parts of the country are frequently experiencing higher temperatures than they used to, like regular 100-degree days in Colorado that used to be an extreme outlier. Places are also seeing weather patterns that are completely out of sync with their historical climate. In fact, a consequence of climate change is more erratic weather patterns, including wild snowstorms and anomalies like the polar vortex reaching farther south or a heatwave in the Pacific Northwest that rivals temperatures typically seen in Death Valley, California.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "Global warming. Climate change. Climate crisis. No matter how you refer to the threat, they are all related. The average temperature of the Earths surface has increased significantly since the 1880s (i.e., global warming). This has led to significant changes to the long-term weather patterns, or climate, of regions across the globe (i.e., climate change). And due to the consequences of climate change (e.g., drought, flooding, melting sea ice, disease, etc.), some consider the threat a genuine global crisis (i.e., climate crisis). No matter what we call it, the science is clear that our world is changing because of increased greenhouse gases in the atmosphere", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "Explore all the amazing climate change research the USGS is doing through the Climate Science Explorer page.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "There are many “natural” and “anthropogenic” (human-induced) factors that contribute to climate change. Climate change has always happened on Earth, which is clearly seen in the geological record; it is the rapid rate and the magnitude of climate change occurring now that is of great concern worldwide. Greenhouse gases in the atmosphere absorb heat radiation. Human activity has increased...", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "Although people tend to use these terms interchangeably, global warming is just one aspect of climate change. “Global warming” refers to the rise in global temperatures due mainly to the increasing concentrations of greenhouse gases in the atmosphere. “Climate change” refers to the increasing changes in the measures of climate over a long period of time including precipitation, temperature, and...", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "How can climate change affect natural disasters? With increasing global surface temperatures the possibility of more droughts and increased intensity of storms will likely occur. As more water vapor is evaporated into the atmosphere it becomes fuel for more powerful storms to develop. More heat in the atmosphere and warmer ocean surface temperatures can lead to increased wind speeds in tropical storms. Rising sea levels expose higher locations...link  How can climate change affect natural disasters? With increasing global surface temperatures the possibility of more droughts and increased intensity of storms will likely occur. As more water vapor is evaporated into the atmosphere it becomes fuel for more powerful storms to develop. More heat in the atmosphere and warmer ocean surface temperatures can lead to increased wind speeds in tropical storms. Rising sea levels expose higher locations...", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "What are some of the signs of climate change? • Temperatures are rising world-wide due to greenhouse gases trapping more heat in the atmosphere.• Droughts are becoming longer and more extreme around the world.• Tropical storms becoming more severe due to warmer ocean water temperatures.• As temperatures rise there is less snowpack in mountain ranges and polar areas and the snow melts faster.• Overall, glaciers are melting at a faster rate.•...link  What are some of the signs of climate change? • Temperatures are rising world-wide due to greenhouse gases trapping more heat in the atmosphere.• Droughts are becoming longer and more extreme around the world.• Tropical storms becoming more severe due to warmer ocean water temperatures.• As temperatures rise there is less snowpack in mountain ranges and polar areas and the snow melts faster.• Overall, glaciers are melting at a faster rate.", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "What are the long-term effects of climate change? Scientists have predicted that long-term effects of climate change will include a decrease in sea ice and an increase in permafrost thawing, an increase in heat waves and heavy precipitation, and decreased water resources in semi-arid regions. Below are some of the regional impacts of global change forecast by the Intergovernmental Panel on Climate Change: North America: Decreasing snowpack in the...link  What are the long-term effects of climate change? Scientists have predicted that long-term effects of climate change will include a decrease in sea ice and an increase in permafrost thawing, an increase in heat waves and heavy precipitation, and decreased water resources in semi-arid regions. Below are some of the regional impacts of global change forecast by the Intergovernmental Panel on Climate Change: North America: Decreasing snowpack in the...", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "What is the difference between global warming and climate change? Although people tend to use these terms interchangeably, global warming is just one aspect of climate change. “Global warming” refers to the rise in global temperatures due mainly to the increasing concentrations of greenhouse gases in the atmosphere. “Climate change” refers to the increasing changes in the measures of climate over a long period of time including precipitation, temperature, and...link  What is the difference between global warming and climate change? Although people tend to use these terms interchangeably, global warming is just one aspect of climate change. “Global warming” refers to the rise in global temperatures due mainly to the increasing concentrations of greenhouse gases in the atmosphere. “Climate change” refers to the increasing changes in the measures of climate over a long period of time including precipitation, temperature, and...Learn More", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},
    {"texto": "The impacts of a changing climate on wildlife and associated ecosystems have yet to be fully determined but changes are clearly underway as are a variety of investigations to assess how we can best preserve key resources while effectively managing others. Using a variety of tools and a combination of studies including adaptive management, long-term monitoring, mathematical modeling, and...link April 9, 2018  Climate ChangeThe impacts of a changing climate on wildlife and associated ecosystems have yet to be fully determined but changes are clearly underway as are a variety of investigations to assess how we can best preserve key resources while effectively managing others. Using a variety of tools and a combination of studies including adaptive management, long-term monitoring, mathematical modeling, and...", "categoria": "climate", "agencia":"USGS", "topico": "climate-change-101"},

    {"texto": "An Ecosystem of Minority Health and Health Disparities Resources", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "Recognizing the need for high-quality, publicly available online resources for improving minority health and reducing health disparities, NIMHD developed HDPulse.", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "Researchers in academic institutions, research organizations, or federal organizationsPublic health practitioners (program implementers)Healthcare providers (clinicians, nurses, behavioral health providers)", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "Purpose: Provides a tool to characterize health disparities to motivate action to reduce health disparities. Interactive graphics and maps provide visual support for deciding where to focus public health disparities control efforts.", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "The Data Portal offers quick, easy access to descriptive statistics, interactive graphics, and maps that present health disparities across the nation, states and counties. With easy navigation and a mobile-friendly interface that offers several ways to view and download health disparity data, the portal will provide opportunities to explore health disparity topics such as screening and risk factors, socio-demographics, and mortality—with more to come!", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "Purpose: Provides easy access to interventions that have demonstrated effect to improve minority health or reduce health disparities, along with related publications, products and materials.", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    {"texto": "The Interventions Portal can inform the design, implementation, evaluation, dissemination, and adaptation of interventions to improve minority health and reduce health disparities. Minority health and health disparities researchers, program planners, and intervention developers can submit, find, sort, and download evidence-based interventions and resources. Coming soon!", "categoria": "health", "agencia":"NIH", "topico": "ecosistema"},
    
    {"texto": "American Meteorological Society Graduate Fellowship", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "Applicants must be seeking degrees in the fields of atmospheric sciences, chemistry, computer sciences, engineering, environmental sciences, hydrology, mathematics, oceanography, and physics. NOAA's Climate Program Office provides funding to support three AMS graduate fellows per year.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "he NOAA Central Library offers a wide variety of internship and volunteer opportunities for students interested in library sciences, information management, or NOAA's mission.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "They have a variety of projects that will help students develop research, analytic, and technical skills.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "Chesapeake Bay Summer Internship Program", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "Each summer, NOAA Chesapeake Bay Office, in partnership with the Chesapeake Research Consortium, offers several paid summer internships primarily geared toward current undergraduate students. Internships focus on scientific field research to resource management and policy.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "CRC Chesapeake Student Recruitment, Early Advisement, and Mentoring (C-StREAM) program is focused on recruiting, advising, and mentoring college students from populations who have been historically excluded from the environmental field and are underrepresented in environmental research and management professions.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    {"texto": "For the purpose of this program, C-StREAM focuses on assisting students who identify as people of color and/or who are first generation college students.", "categoria": "meteorological", "agencia":"NOAA", "topico": "research"},
    
    {"texto": "Americans have clean air, land and water;", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "National efforts to reduce environmental risks are based on the best available scientific information", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "Federal laws protecting human health and the environment are administered and enforced fairly, effectively and as Congress intended;", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "Environmental stewardship is integral to U.S. policies concerning natural resources, human health, economic growth, energy, transportation, agriculture, industry, and international trade, and these factors are similarly considered in establishing environmental policy;", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "All parts of society--communities, individuals, businesses, and state, local and tribal governments--have access to accurate information sufficient to effectively participate in managing human health and environmental risks;", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "Contaminated lands and toxic sites are cleaned up by potentially responsible parties and revitalized; and", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "Chemicals in the marketplace are reviewed for safety.", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "When Congress writes an environmental law, we implement it by writing regulations.", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "Often, we set national standards that states and tribes enforce through their own regulations. If they fail to meet the national standards, we can help them. We also enforce our regulations, and help companies understand the requirements.", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},
    {"texto": "At laboratories located throughout the nation, we identify and try to solve environmental problems. To learn even more, we share information with other countries, private sector organizations, academic institutions, and other agencies.", "categoria": "environment", "agencia":"EPA", "topico": "ambiente"},

]

textos = [item["texto"] for item in dados_rotulados]
categorias = [item["categoria"] for item in dados_rotulados]
agencias = [item["agencia"] for item in dados_rotulados]
topicos = [item["topico"] for item in dados_rotulados]

vetorizador = TfidfVectorizer()
X = vetorizador.fit_transform(textos)

modelo_categoria = MultinomialNB()
modelo_categoria.fit(X, categorias)

modelo_agencia = MultinomialNB()
modelo_agencia.fit(X, agencias)

modelo_topico = MultinomialNB()
modelo_topico.fit(X, topicos)

def fazer_previsao(frase):
    frase_preprocessada = preprocessar_frase(frase)
    
    vetor_frase = vetorizador.transform([frase_preprocessada])
    
    categoria_predita = modelo_categoria.predict(vetor_frase)
    agencia_predita = modelo_agencia.predict(vetor_frase)
    topico_predito = modelo_topico.predict(vetor_frase)
    
    return categoria_predita, agencia_predita, topico_predito

nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

def preprocessar_frase(frase):
    tokens = word_tokenize(frase)
    
    tokens = [token.lower() for token in tokens]
    
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token.isalnum() and token not in stop_words]
    
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    frase_processada = ' '.join(tokens)
    
    return frase_processada

frase_usuario = "EPA"
categoria_predita, agencia_predita, topico_predito = fazer_previsao(frase_usuario)

print("Categoria Predita:", categoria_predita)
print("Agência Predita:", agencia_predita)
print("Tópico Predito:", topico_predito)